### ISSUE TITLE
Toggle visibility

### ISSUE THREAD

**Issue by Irubataru** [utilyre/barbecue.nvim#10]
Hi! I was playing around with getting a zen-mode plugin up and running for focused writing (Ataraxis-mode on [true-zen](https://github.com/Pocco81/true-zen.nvim), used to use [Goyo.vim](https://github.com/junegunn/goyo.vim)), and if I enable that then the only status bar I have left is barbecue. Is there a simple way to hide it? Ideally I want to be able to toggle it so I can hide it when I enter the mode, and enable it again when I leave.

**Comment by utilyre** [comment]
Hello. I've implemented this through both a lua api and a user command:

- [User Commands](https://github.com/utilyre/barbecue.nvim/tree/32b29cab4234f635710dcefda45d641a78bc43a7#commands)

- API

  ```lua
  require'barbecue'.toggle([shown: boolean])

  for _, winnr in ipairs(vim.api.nvim_list_wins()) do
    require'barbecue'.update(winnr)
  end
  ```

**Comment by Irubataru** [comment]
Wow, that was very quick! I added it to my config just now and it works great, thank you so much <3

**Comment by utilyre** [comment]
Commenting this because I think github hasn't notified you for the edition of my previous comment. That weird for loop over windows is now moved inside the `toggle` function, therefore you can remove it from your config.
