### ISSUE TITLE
Allow disabling of nvim-navic

### ISSUE THREAD

**Issue by dlvhdr** [utilyre/barbecue.nvim#12]
I like to use nvim-navic for stuff othan the my winbar, and I do not want it to be in it.
E.g. I might want to show the navic "gps" on a keymap.
If I have it installed, `barbecue` picks it up and I can't disable that.

**Comment by utilyre** [comment]
Alright, now you are now able to customize navic through navic.setup() as you like (it won't have any side effects on barbecue).

In order to hide/show barbecue, run the following

```lua
require("barbecue.ui").toggle([true|false])
```

or

```vim
:Barbecue {toggle|hide|show}
```

**Comment by dlvhdr** [comment]
Thanks! I think the `attach_navic` config prop works!
