### ISSUE TITLE
[Enhancement] Hide or map certain directories and paths

### ISSUE THREAD

**Issue by olimorris** [utilyre/barbecue.nvim#13]
Firstly, what a fantastic plugin this is and thanks for a well put together `README`.

With the VS Code equivalent winbar, you have the benefit of having a smaller font to the rest of the editor; this allows for you to fit more "context" into the bar. We don't have that luxury in Neovim and everything is the same size, making space that little bit more precious.

If I take my dotfiles as an example:

<img width="1350" alt="Screen Shot 2022-11-03 at 09 03 24@2x" src="https://user-images.githubusercontent.com/9512444/199682786-d5714b0e-0006-4985-9cb1-7aa9be4cd6ac.png">

When editing them, I am pretty much always in the `~/.config/nvim/lua` namespace. I'd like to omit that from the winbar or perhaps map it to something like `Neovim`, to save space. If I deviate from that, then just display the path as-is.

**Comment by utilyre** [comment]
I am currently working on a way to truncate some entries as needed. However for your specific case this is the solution:

```lua
barbecue.setup({
  modifiers = {
    dirname = ":~:.:s?.config/nvim/lua?Neovim?",
  },
})
```

**Comment by utilyre** [comment]
Closing this in favor of #16.
