### ISSUE TITLE
`E5108: Error executing lua vim/shared.lua:0: after the second argument: expected table, got nil`

### ISSUE THREAD

**Issue by hanselch** [utilyre/barbecue.nvim#15]
Have all the dependencies and updated them all, used Plug to install both barbecue and it's dependencies. Still popping up this error:
```
E5108: Error executing lua vim/shared.lua:0: after the second argument: expected table, got nil
stack traceback:
        [C]: in function 'error'
        vim/shared.lua: in function 'validate'
        vim/shared.lua: in function 'tbl_deep_extend'
        ...oload/plugged/barbecue.nvim/lua/barbecue/config/init.lua:21: in function 'apply'
        ...vim/autoload/plugged/barbecue.nvim/lua/barbecue/init.lua:65: in function 'setup'
```

Looks like the argument `table` wasn't used. Referring to these two:
```lua
function Config.prototype:apply(cfg)
  self.user = vim.tbl_deep_extend("force", self.template, cfg)
end
```
```lua
function M.setup(cfg)
  config:apply(cfg)
  --- ...
```

**Comment by utilyre** [comment]
I've done some major refactoring recently. Would you mind updating to the latest commit and leaving the error message again?

**Comment by hanselch** [comment]
```
E5108: Error executing lua vim/shared.lua:0: after the second argument: expected table, got nil
stack traceback:
        [C]: in function 'error'
        vim/shared.lua: in function 'validate'
        vim/shared.lua: in function 'tbl_deep_extend'
        ...oload/plugged/barbecue.nvim/lua/barbecue/config/init.lua:13: in function 'apply_config'
        ...vim/autoload/plugged/barbecue.nvim/lua/barbecue/init.lua:31: in function 'setup'
        [string ":lua"]:2: in main chunk
```

Referring again to the two:

`...oload/plugged/barbecue.nvim/lua/barbecue/config/init.lua:13: in function 'apply_config'`
```lua
---merges `cfg` into `template` and sets it as `user`
---@param cfg BarbecueTemplateConfig
function M.apply_config(cfg)
  M.user = vim.tbl_deep_extend("force", template, cfg)
end
```

`...vim/autoload/plugged/barbecue.nvim/lua/barbecue/init.lua:31: in function 'setup'`
```lua
---configures and starts barbecue
---@param cfg BarbecueTemplateConfig
function M.setup(cfg)
  config.apply_config(cfg)
  config.resort_highlights()
```

**Comment by insomnia-creator** [comment]
Same here:

`packer.nvim: Error running config for barbecue.nvim: vim/shared.lua:0: after the second argument: expected table, got nil`

Neovim version `NVIM v0.9.0-dev-16-g56998feeb`
Compiled it myself.

**Comment by utilyre** [comment]
Should be fixed now.

**Comment by insomnia-creator** [comment]
I'll check it out.

**Comment by hanselch** [comment]
Sorry for the late reply
---
```
E5108: Error executing lua ...vim/autoload/plugged/barbecue.nvim/lua/barbecue/init.lua:37: unexpected event
stack traceback:
        [C]: in function 'nvim_create_autocmd'
        ...vim/autoload/plugged/barbecue.nvim/lua/barbecue/init.lua:37: in function 'setup'
        [string ":lua"]:2: in main chunk
```

This time, the `nvim_create_autocmd` is giving trouble here:

```lua
if config.user.attach_navic then
    vim.api.nvim_create_autocmd("LspAttach", { -- <--- Possibly here?
      group = augroup,
      callback = function(a)
        local client = vim.lsp.get_client_by_id(a.data.client_id)
        if client.server_capabilities["documentSymbolProvider"] then navic.attach(client, a.buf) end
      end,
    })
  end
```

Might be simething to do w/ `LspAttach`?

**Comment by utilyre** [comment]
> Sorry for the late reply
> 
> ```
> E5108: Error executing lua ...vim/autoload/plugged/barbecue.nvim/lua/barbecue/init.lua:37: unexpected event
> stack traceback:
>         [C]: in function 'nvim_create_autocmd'
>         ...vim/autoload/plugged/barbecue.nvim/lua/barbecue/init.lua:37: in function 'setup'
>         [string ":lua"]:2: in main chunk
> ```
> 
> This time, the `nvim_create_autocmd` is giving trouble here:
> 
> ```lua
> if config.user.attach_navic then
>     vim.api.nvim_create_autocmd("LspAttach", { -- <--- Possibly here?
>       group = augroup,
>       callback = function(a)
>         local client = vim.lsp.get_client_by_id(a.data.client_id)
>         if client.server_capabilities["documentSymbolProvider"] then navic.attach(client, a.buf) end
>       end,
>     })
>   end
> ```
> 
> Might be something to do w/ `LspAttach`?

Could you open another issue and include what version of neovim you are using?

**Comment by utilyre** [comment]
I'll close this thread since this specific issue has been solved.

**Comment by hanselch** [comment]
Mkay, it was my mistake, didn't updated `neovim` to v0.8+.

Thought I've update 0.8 since it was released in back in September. The `AppImage` didn't compile it correctly (maybe made it unsafe too...).

I am so sorry for this unnecessary goose chase. Though now it looking back from the past releases, optimization has improved! So these changes is an improvement!

Again, I am so sorry for the massive wild goose chase!

**Comment by insomnia-creator** [comment]
I was on v0.9 and this error still happened to me.

**Comment by utilyre** [comment]
> I was on v0.9 and this error still happened to me.

I suppose you mean the `LspAttach` error. If that's the case consider opening another issue for that.

**Comment by insomnia-creator** [comment]
It was the exact same error @hanselch had. It was working fine after the commit fixing the said issue
