### ISSUE TITLE
If there was some sort of truncation, how would you like it to be?

### ISSUE THREAD

**Issue by utilyre** [utilyre/barbecue.nvim#16]
Files with long paths or JSON documents in which there is so much nesting can be really annoying in  winbar. So what do you think is needed to be done for this problem?

I leave my ideas here but feel free to comment your own idea

1. A function in the config that receives the width of the current window along side the current length of winbar (including custom_section) and returns a number that indicates how many "entries" will be truncated.
2. Same as previous but have different functions for `dirname`, `filename`, and `context`.
3. An automatic logic that truncates as much characters as needed (from less crucial parts) in order to prevent Neovim from truncating the winbar itself.

Since I'm really busy with my lessons these days, I'm gonna need some time and also help from you guys to solve this issue.

**Comment by olimorris** [comment]
My personal, ideal, winbar would be one where `Barbecue` is truncated when the value of `Barbecue + Nvim-Navic` exceeds the window width.

Not sure where that fits into the options.

**Comment by kagbodji** [comment]
Personally, I'd want option 3. A simple implementation where Barbecue truncates from the beginning of the crumb until it fits in the view works. I can easily jump backwards to reveal more of the truncated parts.

for example:
```
one > long > line > that > would > not > fit > the viewport
```
```
... > not >  fit > the viewport
```

**Comment by olimorris** [comment]
@kagbodji has explained perfectly, what I was trying to say 😄

**Comment by utilyre** [comment]
I really appreciate your cool ideas.

What do you think about this other method that I just came up with

> First truncate from the beginning of `dirname` until the text fits into the winbar. In case there isn't enough room yet, start truncating the `context` from the beginning.

This would be how it looks:

```
... > init.lua > ... > 1st nest > 2nd nest
```

The reason I'm insisting on keeping the `filename` is that I know some people (including myself) use it to know what file is on what window in case of splitting.

**Comment by olimorris** [comment]
> ```
> ... > init.lua > ... > 1st nest > 2nd nest
> ```
> 
> The reason I'm insisting on keeping the `filename` is that I know some people (including myself) use it to know what file is on what window in case of splitting.

I think that makes complete sense and I'd be happy with this.

Would you consider this being a configuration option though? I have buffers in the tabline so can visually see where I am and may appreciate the extra text available in the winbar.

**Comment by utilyre** [comment]
> > ```
> > ... > init.lua > ... > 1st nest > 2nd nest
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The reason I'm insisting on keeping the `filename` is that I know some people (including myself) use it to know what file is on what window in case of splitting.
> 
> I think that makes complete sense and I'd be happy with this.
> 
> Would you consider this being a configuration option though? I have buffers in the tabline so can visually see where I am and may appreciate the extra text available in the winbar.

That seems like a good idea. I'll make the whole feature (for extra performance) and the truncation of `filename` optional in the config.

**Comment by utilyre** [comment]
The "simple" method seems stable. Please checkout `feature/truncation` in your package manager to contribute to testing this feature.

By the way, the second part of #19 (`modified` symbol at the beginning) is now the default. I might try to implement the previous behavior later and make it optional.

**Comment by kagbodji** [comment]
> The "simple" method seems stable. Please checkout feature/truncation in your package manager to contribute to testing this feature.

works like a charm!! Thank you so much for adding this so quickly! And the bonus of the modified symbol at the beginning is very welcome 😃.

<img width="614" alt="image" src="https://user-images.githubusercontent.com/30058890/204123548-492e9a88-55db-4ad1-afc5-3b536332b2dd.png">

The `keep_basename` method does not seem to work yet as of my testing, but I personally only need the `simple` option as the tab line already contains the filename.

**Comment by utilyre** [comment]
I'm glad you liked it.

> The keep_basename method does not seem to work yet as of my testing, but I personally only need the simple option as the tab line already contains the filename.

It is implemented now.

**Comment by utilyre** [comment]
Since the PR is done, I'm closing this issue.
