### ISSUE TITLE
Different highlights for file path and code context.

### ISSUE THREAD

**Issue by kagbodji** [utilyre/barbecue.nvim#19]
Hi there, thanks for this awesome plugin! My wishful request: I would like to highlight the file path separately from the code context. I.e.,

`path` > `to` > `foo.lua` > this > is > a > method context.

In addition, it would be awesome if the "buffer modified" indicator could be configured to appear in the beginning of the path, as opposed to the end as currently implemented.  i.e., 

`+` `path` > `to` > `foo.lua` > this > is > a > method context

where `+` is the modification indicator.

Thanks!

**Comment by utilyre** [comment]
Try setting `BarbecueDirname`, `BarbecueBasename`, and `BarbecueBasename` highlight groups.
