### ISSUE TITLE
Just started to get this error in barbacue:  ...\init.lua:13: attempt to index field 'symbols' (a nil value)

### ISSUE THREAD

**Issue by pablogipi** [utilyre/barbecue.nvim#21]
Hello.
Im not sure if this is because another plugin that barbacue depends on has been updated recently bu I have started to get this error:
`packer.nvim: Error running config for barbecue.nvim: ...\packer\start\barbecue.nvim/lua\barbecue\config\init.lua:13: attempt to index field 'symbols' (a nil value)`
I have to comment lines 13-15 in `barbecue.nvim/lua\barbecue\config\init.lua` to get the plugin working again without errors.
Any idea where this error can come from?
Thanks

**Comment by space-blaster** [comment]
same here

**Comment by RunningIkkyu** [comment]
Got the same error on Neovim 0.7.0  (mac)

**Comment by craigrosie** [comment]
Also getting this issue on a fresh install of barbecue. Using neovim 0.8.1 on mac & debian.

**Comment by pablogipi** [comment]
I'm on Neovim 0.8 on Windows.

**Comment by pseudoparenchymatous** [comment]
Same. It's because of this change:
fa891029b4d9614d094585add95e7c59c93f0a47

**Comment by MarWeUMR** [comment]
A quick and dirty fix in `~/.local/share/nvim/site/pack/packer/start/barbecue.nvim/lua/barbecue/config/init.lua` (add check that `cfg.symbols` is not nil:
```
function M.apply_config(cfg)
  if cfg.symbols ~= nil then
    if cfg.symbols.default_context ~= nil then
      vim.notify(
        "symbols.default_context is deprecated, please remove it from your barbecue config",
        vim.log.levels.WARN
      )
    end
  end

  M.user = vim.tbl_deep_extend("force", template, cfg)
end
```

I'm not experienced with neovim internals nor lua, so this might be bad style, but it works for the moment.

**Comment by pseudoparenchymatous** [comment]
> A quick and dirty fix in `~/.local/share/nvim/site/pack/packer/start/barbecue.nvim/lua/barbecue/config/init.lua` (add check that `cfg.symbols` is not nil:
> 
> ```
> function M.apply_config(cfg)
>   if cfg.symbols ~= nil then
>     if cfg.symbols.default_context ~= nil then
>       vim.notify(
>         "symbols.default_context is deprecated, please remove it from your barbecue config",
>         vim.log.levels.WARN
>       )
>     end
>   end
> 
>   M.user = vim.tbl_deep_extend("force", template, cfg)
> end
> ```
> 
> I'm not experienced with neovim internals nor lua, so this might be bad style, but it works for the moment.

You're editing the file that packer downloaded for you? 😂

**Comment by MarWeUMR** [comment]
> You're editing the file that packer downloaded for you? 😂
What alternatives are there?
Either pin the plugin to an older commit, make a fork, change code and use the custom plugin, or make a quick fix in the packer files until the real fix comes in and overwrites it. What am I missing here?

**Comment by pablogipi** [comment]
> > You're editing the file that packer downloaded for you? 😂
> 
> What alternatives are there? Either pin the plugin to an older commit, make a fork, change code and use the custom plugin, or make a quick fix in the packer files until the real fix comes in and overwrites it. What am I missing here?

Yep I also did something similar, temporaly, waiting for a proper fix that we can pull, which seems to be there now ....

**Comment by pablogipi** [comment]
Thanks for the prompt fix @utilyre
