### ISSUE TITLE
the plugin breaks with files with no extension

### ISSUE THREAD

**Issue by Rishabh672003** [utilyre/barbecue.nvim#24]
![image](https://user-images.githubusercontent.com/53911515/204871299-1b8261dc-e5bc-4845-ae89-6fd2057b7627.png)
i reproduced the same issue while opening other files with no extension

**Comment by utilyre** [comment]
Yep, it's been fixed on the `dev` branch (#22).

**Comment by utilyre** [comment]
It's on `main` now.

**Comment by Rishabh672003** [comment]
thanks @utilyre for your great work
