### ISSUE TITLE
Missing default value handling for .setup()

### ISSUE THREAD

**Issue by Irubataru** [utilyre/barbecue.nvim#3]
It seems like you don't default to an empty value if you call setup with no arguments. Maybe you can add a simple

```lua
if config == nil then
  config = {}
end
```

at the beginning of the setup function.

By the way, which font is the separator from? I use a nerdfont font, but it is still a box for me.

**Comment by utilyre** [comment]
> By the way, which font is the separator from? I use a nerdfont font, but it is still a box for me.

See [vscode-codicons](https://github.com/microsoft/vscode-codicons). Inside the dist folder you can find the font.
