### ISSUE TITLE
Add highlight group for the remainder of the bar

### ISSUE THREAD

**Issue by ebkalderon** [utilyre/barbecue.nvim#30]
I'm currently trying to set a uniform `bg` highlight color for all components in the entire winbar, but I can't find any way to do so. While I can manually set the `bg` color for each of the `WinBar` and `Barbecue*` highlight groups individually, there isn't any highlight group which handles the remainder of the winbar.

Looking inside the `vim.schedule()` callback at the bottom of `lua/barbecue/ui.lua`, I see that `winbar` has `%#Normal#%=` appended to it before the `custom_section` is run, which means I can't change it out for a different highlight group after the fact. It would be nice if `%#Normal#%=` was replaced with `%#BarbecueRemainder#%=` (feel free to bikeshed the name) where `BarbecueRemainder` is linked to `Normal` by default. This would allow users to redefine said highlight group to whatever they wish if they'd like to customize the bar's background color.

Many thanks for this awesome plugin. :heart:

**Comment by utilyre** [comment]
Checkout `dev` branch and see if this is what you want.

**Comment by ebkalderon** [comment]
This is terrific! Thank you so much. It works great on my side. Given the following configuration using my own [personal dotfiles](https://github.com/ebkalderon/dotfiles):

```lua
local background = "#272822"
vim.api.nvim_set_hl(0, "BarbecueNormal", { bg = background })
vim.api.nvim_set_hl(0, "BarbecueBasename", { fg = "#f8f8f2", bg = background })
vim.api.nvim_set_hl(0, "BarbecueContext", { fg = "#bcbcbc", bg = background })
vim.api.nvim_set_hl(0, "BarbecueDirname", { fg = "#75715e", bg = background })
vim.api.nvim_set_hl(0, "BarbecueEllipsis", { link = "BarbecueDirname" })
vim.api.nvim_set_hl(0, "BarbecueModified", { fg = "#e6db74", bg = background })
vim.api.nvim_set_hl(0, "BarbecueSeparator", { link = "BarbecueDirname" })
```

I see the following result:

![Screenshot from 2022-12-08 00-36-58](https://user-images.githubusercontent.com/322831/206365328-3c7fcb8c-1fc9-4b3c-8f2e-a4d0f470c51b.png)

I did notice, however, that the context type icons and the filetype icons from `nvim-dev-webicons` have the wrong background color.

I believe I can override the other `BarbecueContext.*` groups using a loop which looks up each group by name using `vim.api.nvim_get_hl_by_name()`, normalizes the returned object (especially for highlight groups that `link` to others) so that it matches what `vim.api.nvim_set_hl()` expects, appends/overrides the `bg` value, and applies it. However, I'm not too sure how to update the `DevIcon.*` groups as well, without being too verbose or repetitive. I suppose I could set up a `FileType` autocmd which looks up the highlight group with:

```lua
local bufnr = vim.api.nvim_get_current_buf()
let _, name = require("nvim-dev-webicons").get_icon_by_filetype(vim.bo[bufnr].filetype)
if name ~= nil then
  local highlight = vim.api.nvim_get_hl_by_name(name, true)

  highlight.fg = highlight.foreground
  highlight.foreground = nil
  highlight.bg = "#272822"
  highlight.background = nil

  vim.api.nvim_set_hl(0, name, highlight)
end
```

This would lazily update the background color for each filetype icon as new files get opened.

I believe all this could work, but I'm wondering whether you have any better ideas on how to approach this.

**Comment by utilyre** [comment]
That is a fair point. I guess I'll have to implement the hl groups just like how lualine does it.

As a result we'll have a new option called `theme` in the config that takes color codes and then barbecue will create needed highlight groups on the fly.

In addition I'll also add support for a `barbecue.theme` module to allow colorschemes define the color codes outside of the user configurations.

However, I still need to put more thoughts into this and find some free time for getting it done.

**Comment by utilyre** [comment]
I'll reopen for recalling myself to implement the feature.

**Comment by patilatharva** [comment]
+1 on the `themes` feature idea - that would be a game changer for the winbar

**Comment by utilyre** [comment]
I've made some change.

To get started copy the `barbecue.theme.default` module to `barbecue.theme.[colorscheme]` in which `[colorscheme]` is the exact name of your current colorscheme (`lua print(vim.g.colors_name)`).

**Comment by utilyre** [comment]
Btw, I'm making a PR for folke's tokyonight theme. I'll include it down below as an example (feel free to recommend any changes you'd like to be done on it)

```lua
local c = require("tokyonight.colors").setup({ transform = true })

local tokyonight = {}

tokyonight.normal = { bg = c.none, fg = c.fg_dark }
tokyonight.modified = { fg = c.warning }
tokyonight.ellipsis = { fg = c.dark5 }
tokyonight.separator = { fg = c.dark5 }
tokyonight.dirname = { fg = c.dark5 }
tokyonight.basename = { fg = c.fg_dark, bold = true }
tokyonight.context = { fg = c.fg_dark }

tokyonight.context_file = { fg = c.fg_dark }
tokyonight.context_module = { fg = c.yellow }
tokyonight.context_namespace = { fg = c.yellow }
tokyonight.context_package = { fg = c.blue }
tokyonight.context_class = { fg = c.orange }
tokyonight.context_method = { fg = c.blue }
tokyonight.context_property = { fg = c.green1 }
tokyonight.context_field = { fg = c.green1 }
tokyonight.context_constructor = { fg = c.blue }
tokyonight.context_enum = { fg = c.orange }
tokyonight.context_interface = { fg = c.orange }
tokyonight.context_function = { fg = c.blue }
tokyonight.context_variable = { fg = c.magenta }
tokyonight.context_constant = { fg = c.magenta }
tokyonight.context_string = { fg = c.green }
tokyonight.context_number = { fg = c.orange }
tokyonight.context_boolean = { fg = c.orange }
tokyonight.context_array = { fg = c.orange }
tokyonight.context_object = { fg = c.orange }
tokyonight.context_key = { fg = c.purple }
tokyonight.context_null = { fg = c.orange }
tokyonight.context_enum_member = { fg = c.green1 }
tokyonight.context_struct = { fg = c.orange }
tokyonight.context_event = { fg = c.orange }
tokyonight.context_operator = { fg = c.green1 }
tokyonight.context_type_parameter = { fg = c.green1 }

return tokyonight
```

![20221227-001627](https://user-images.githubusercontent.com/91974155/209583886-212427c1-88b4-46ea-80ec-ca22d445e3be.png)
