### ISSUE TITLE
An error occurred after updating the plug-in.

### ISSUE THREAD

**Issue by zetatez** [utilyre/barbecue.nvim#40]
An error occurred after updating the plug-in.

```
Error executing vim.schedule lua callback: ...acker/start/barbecue.nvim/lua/barbecue/ui/components.lua:26: invalid key:
stack traceback:
        [C]: in function 'nvim_set_hl'
        ...acker/start/barbecue.nvim/lua/barbecue/ui/components.lua:26: in function 'get_file_icon'
        ...acker/start/barbecue.nvim/lua/barbecue/ui/components.lua:110: in function 'get_basename'
        ...site/pack/packer/start/barbecue.nvim/lua/barbecue/ui.lua:62: in function 'create_entries'
        ...site/pack/packer/start/barbecue.nvim/lua/barbecue/ui.lua:146: in function <...site/pack/packer/start/barbecue.nvim/lua/barbecue/ui.lua:135>
```

**Comment by utilyre** [comment]
Please provide more context (your config or probably a [repro](https://github.com/folke/lazy.nvim/wiki/Minimal-%60init.lua%60-to-Reproduce-an-Issue))?

**Comment by zetatez** [comment]
I use the default setting:
```
require("barbecue").setup({})
```

**Comment by zetatez** [comment]
It works well after commenting the following code
```bash
vim +26 .local/share/nvim/site/pack/packer/start/barbecue.nvim/lua/barbecue/ui/components.lua
```
```lua
    -- vim.api.nvim_set_hl(
    --   0,
    --   theme.highlights[key],
    --   vim.tbl_extend(
    --     "force",
    --     vim.api.nvim_get_hl_by_name(theme.highlights.normal, true),
    --     vim.api.nvim_get_hl_by_name(devicons_highlight, true)
    --   )
    -- )
```

**Comment by Rishabh672003** [comment]
am getting the same error @utilyre 
![image](https://user-images.githubusercontent.com/53911515/210085566-820cb3ee-b780-4d67-ac1f-ee813a2bafdb.png)

**Comment by Rishabh672003** [comment]
https://github.com/utilyre/barbecue.nvim/commit/d67e116e6113735fb11f236d4439d7e06b5596af this commit broke something idk what

**Comment by Rishabh672003** [comment]
![image](https://user-images.githubusercontent.com/53911515/210089550-4e28570c-62da-4009-9e97-dc3dcf8d3031.png)
also many of my icons have no color (i guess i should open a new issue for that)

**Comment by nyngwang** [comment]
@utilyre I got exactly the same issue after the update.

**Comment by utilyre** [comment]
I'm trying to reproduce this but no luck yet. May I have a **SINGLE** minimal config that produces the bug? (see [lazy](https://github.com/folke/lazy.nvim/wiki/Minimal-%60init.lua%60-to-Reproduce-an-Issue) as mentioned before)

For the theming issue, see the latest pr (#39). Generally whenever a big update is pushed and is named "Merge pull request from utilyre/dev" please first refer to the pr and see if there was any breaking changes.

Also please don't mix up issues. The theme being broken should've been a totally separate issue.

**Comment by nyngwang** [comment]
Oh, I should not mention the issue @Rishabh672003 has mentioned(But I just meant his observation is right). The config I provided is to reproduce the problem as [OP](https://github.com/utilyre/barbecue.nvim/issues/40#issue-1514514646).

**Comment by nyngwang** [comment]
To @utilyre:

> I'm trying to reproduce this but no luck yet. [...]

I just did:

```lua
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  -- do not remove the colorscheme!
  "folke/tokyonight.nvim",
  -- add any other pugins here
  {
    'utilyre/barbecue.nvim',
    dependencies = {
      'neovim/nvim-lspconfig',
      'smiteshp/nvim-navic',
      'kyazdani42/nvim-web-devicons', -- optional
    },
    -- commit = 'c9a16e6',
    config = function()
      require('barbecue').setup {
        attach_navic = false, -- attach navic to LSPs automatically.
        create_autocmd = false,
      }
      vim.api.nvim_create_autocmd({ 'CursorHold' }, {
        callback = function()
          require('barbecue.ui').update()
        end,
      })
    end,
  },
  {
    'neovim/nvim-lspconfig',
    dependencies = {
      'williamboman/mason.nvim',
      'williamboman/mason-lspconfig.nvim',
      'hrsh7th/cmp-nvim-lsp',
    },
    config = function ()
      -- ensure this order.
      require('mason').setup()
      require('mason-lspconfig').setup({
        ensure_installed = {
          'sumneko_lua',
        },
      })
      require('mason-lspconfig').setup_handlers {
        function (server_name)
          require('lspconfig')[server_name].setup {
            capabilities = require('cmp_nvim_lsp').default_capabilities(vim.lsp.protocol.make_client_capabilities()),
            autostart = true,
            on_attach = function (client, bufnr)
              if client.server_capabilities.documentSymbolProvider then
                require('nvim-navic').attach(client, bufnr)
              end
            end,
            settings = {
              Lua = {
                runtime = {
                  version = 'LuaJIT',
                },
                diagnostics = {
                  globals = { 'vim' }
                },
                workspace = {
                  -- Make the server aware of Neovim runtime files
                  library = vim.api.nvim_get_runtime_file('', true),
                  checkThirdParty = false,
                },
                telemetry = {
                  enable = false,
                },
              }
            }
          }
        end,
      }
    end
  }
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

-- add anything else here
vim.opt.termguicolors = true
-- do not remove the colorscheme!
vim.cmd([[colorscheme tokyonight]])
```

<img src="https://user-images.githubusercontent.com/24765272/210125773-04e08864-cc2d-4a43-a997-0f3f032bd74d.png" width="600">

**Comment by nyngwang** [comment]
Hi, all:

I think I found the culprit. It seems that some upstream APIs are not stable. These are the related issues:

- https://github.com/neovim/neovim/issues/18024
- https://github.com/neovim/neovim/issues/18980

I'm pretty sure it's buggy because I just played around with my fork of barbecue.nvim, and some dumpping showed exactly the following, which was mentioned in the two issues :

```
{
    [true] = 6
}
```

**Comment by nyngwang** [comment]
To @zetatez @Rishabh672003:

I played around with [my fork](https://github.com/nyngwang/barbecue.nvim) and now this issue has been resolved:

```
Error executing vim.schedule lua callback: ...acker/start/barbecue.nvim/lua/barbecue/ui/components.lua:26: invalid key:
stack traceback:
        [C]: in function 'nvim_set_hl'
        ...acker/start/barbecue.nvim/lua/barbecue/ui/components.lua:26: in function 'get_file_icon'
        ...acker/start/barbecue.nvim/lua/barbecue/ui/components.lua:110: in function 'get_basename'
        ...site/pack/packer/start/barbecue.nvim/lua/barbecue/ui.lua:62: in function 'create_entries'
        ...site/pack/packer/start/barbecue.nvim/lua/barbecue/ui.lua:146: in function <...site/pack/packer/start/barbecue.nvim/lua/barbecue/ui.lua:135>
```

While, regarding [@Rishabh672003's comment above](https://github.com/utilyre/barbecue.nvim/issues/40#issuecomment-1367985675):

> (img.)
> also many of my icons have no color (i guess i should open a new issue for that also that can be my colorscheme that is catppuccin faults)

Which was so annoying and I just decided to give up. I even hard-coded the stupid theme into the plugin itself: https://github.com/nyngwang/barbecue.nvim/blob/main/lua/barbecue/theme.lua#L4-L40

But I still got everything `cleared`:

<img src="https://user-images.githubusercontent.com/24765272/210137303-e8ced6cf-2dd5-4040-8e41-06647d3c3850.png" width="500">

How about calling this again?

```lua
require('barbecue.theme').load()
```

Well, while I did get those highlight groups set:

<img src="https://user-images.githubusercontent.com/24765272/210137600-adb4067c-b06a-464a-92cd-8293e99a990f.png" width="500">

<img src="https://user-images.githubusercontent.com/24765272/210137623-17534310-2d37-466d-a16a-c17acb1336ff.png" width="500">

But I also got an error:

```
   Error  20:58:35 msg_show.lua_error   require('barbecue.theme').load() E5108: Error executing lua vim/shared.lua:0: after the second argument: expected table, got nil
stack traceback:
	[C]: in function 'error'
	vim/shared.lua: in function 'validate'
	vim/shared.lua: in function 'tbl_extend'
	...cal/share/nvim/lazy/barbecue.nvim/lua/barbecue/theme.lua:108: in function 'load'
	[string ":lua"]:1: in main chunk
```

But I **did** passing a table for it. I even hard-coded it there. Why it was still complaining about `nil`? I don't know.

**Comment by Rishabh672003** [comment]
@nyngwang wow dude thanks for doing so much work you are awesome

**Comment by utilyre** [comment]
Is it working for everyone?

**Comment by erancx** [comment]
seems like groups highlights are broken, I no longer see a proper background.

**Comment by Rishabh672003** [comment]
@erancx i think we should open a new issue for that

**Comment by erancx** [comment]
oh fair enough. was under the impression this was just another symptom to the issue

**Comment by Rishabh672003** [comment]
so yeah this issue can be closed and open a new one for the colorscheme one @zetatez
