### ISSUE TITLE
Add ability to disable nvim-navic in UI

### ISSUE THREAD

**Issue by dlvhdr** [utilyre/barbecue.nvim#43]
I'd like to use barbecue without `nvim-navic`.
I'd like `nvim-navic` to be shown in my statusbar `lualine`.
Currently, if I add a `lualine` navic component, I get them shown up in both `barbecue` and `lualine`.

Appreciate it.

**Comment by utilyre** [comment]
Hi! I just added `show_navic` option. Set it to false and see if works.

**Comment by dlvhdr** [comment]
Just checked and it works! just to note that I had to update my neovim to latest to get it working.

**Comment by nfwyst** [comment]
yes, but still cant prevent load nvim-navic @utilyre
