### ISSUE TITLE
I can't require barbecue from files

### ISSUE THREAD

**Issue by diegoulloao** [utilyre/barbecue.nvim#45]
For some reason the only way to setup barbecue that works for me is the one specified in the documentation:

```lua
use({
  "utilyre/barbecue.nvim",
  branch = "dev", -- omit this if you only want stable updates
  requires = {
    "neovim/nvim-lspconfig",
    "smiteshp/nvim-navic",
    "nvim-tree/nvim-web-devicons", -- optional dependency
  },
  after = "nvim-web-devicons", -- keep this if you're using NvChad
  config = function()
    require("barbecue").setup()
  end,
})
```

But no matter what file is, it can't be required from others.

`plugins/barbecue-nvim.lua`
```lua
require("barbecue").setup()
```

Is throwing this error:
```
Error detected while processing /Users/diego/.config/nvim/init.lua:
module 'barbecue' not found:
        no field package.preload['barbecue']
        ...
```

What I'm doing wrong?

I've done this with a lot of plugins, but this is the only one that's failing...

**Comment by utilyre** [comment]
I'm not quite sure if this is barbecue's fault, since loading modules falls into a lower level being nvim's `rtp` or your plugin manager (in case of lazy.nvim).

**Comment by nyngwang** [comment]
I believe @utilyre is correct. I just saw some updates hours ago with commit messages like these:

```
9e90852 fix(cache): autoloading was broken! (9 hours ago)
...
2d06faa feat(loader): incrementally install missing plugins and rebuild spec, so imported specs from plugins work as expected (13 hours ago)
...
77ff7be perf(cache): cache all lua files till UIEnter instead of VimEnter (14 hours ago)
```
