### ISSUE TITLE
[Enhancement] Specific highlight groups that can be overwritten and supported by colorschemes

### ISSUE THREAD

**Issue by olimorris** [utilyre/barbecue.nvim#47]
Moving #41 to an issue and keen to get other views on this. Acknowledge there has been discussion on this in #30.

**Is your feature request related to a problem? Please describe.**
It's currently difficult to get `barbecue` to match my colorscheme unless that colorscheme has support for it out of the box using `barbecue.Theme`.

**Describe the solution you'd like**
Barbecue used to employ highlights such as `BarbecueModified` and `BarbecueBasename`. This allowed myself, as a [colorscheme maintainer](https://github.com/olimorris/onedarkpro.nvim), to overwrite them to ensure that they matched the overall aesthetic of my colorscheme.

Also, as a user of `barbecue`, it meant that I could easily overwrite the highlights if I wanted something different to the colorscheme's opinion.

**Additional context**
- Most colorscheme's have support for plugins out of the box (see the [`nvim-navic`](https://github.com/olimorris/onedarkpro.nvim/blob/main/lua/onedarkpro/highlights/plugins/nvim_navic.lua) example in my colorscheme)
- For my colorscheme's case, it's simply a matter of matching the plugin's highlight groups to the color palette
- The one exception I make is with [`lualine`](https://github.com/olimorris/onedarkpro.nvim/blob/main/lua/lualine/themes/onedark.lua) which is somethiing I accept as it is one of the most popular plugins in the Neovim community
- However, conforming to a plugin's theming API is far more difficult:
  - It requires me to understand the API fully
  - It requires testing to ensure I've understood it accurately
  - It requires *watching* to in case the API changes and breaks my current support
- Finally, most colorschemes allow users to [overwrite highlight groups](https://github.com/olimorris/onedarkpro.nvim#overriding-highlight-groups) to achieve a great deal of customisation. This is much easier when a plugin exposes highlight groups.

**Summary**
Firstly, I write this issue because I thoroughly value `barbecue` as a plugin and I've missed using it since the `barbecue.Theme` feature was implemented. Secondly, whilst I think that the theming was implemented in good faith, it makes support for the plugin that much more difficult as colorscheme owners need to invest time to understand your API. Finally, I believe it goes against the majority of what other plugin scheme authors do when they expose highlight groups for colorscheme owners to work with.

**Comment by utilyre** [comment]
> Also, as a user of barbecue, it meant that I could easily overwrite the highlights if I wanted something different to the colorscheme's opinion.

I agree. I'll add a guide on readme to make changing colors for the end user easier.

> The one exception I make is with [lualine](https://github.com/olimorris/onedarkpro.nvim/blob/main/lua/lualine/themes/onedark.lua) which is somethiing I accept as it is one of the most popular plugins in the Neovim community

It doesn't matter how popular a plugin is. The thing with `statusline` and `winbar` is that you can't have a real background (say `NormalFloat`). That's why lualine has this workaround to allow users to change the background.

> It requires me to understand the API fully
It requires testing to ensure I've understood it accurately

I do not think following [4 steps](https://github.com/utilyre/barbecue.nvim/blob/1b4a0b6ea6216fee8702857c1e1fcd816abca423/CODE_OF_CONDUCT.md#theming) is **THAT** much complicated.

> It requires watching to in case the API changes and breaks my current support

I can say the same thing for highlight groups. BTW, the theme API is guaranteed not to change until barbecue is versioned.

**Comment by olimorris** [comment]
> > Also, as a user of barbecue, it meant that I could easily overwrite the highlights if I wanted something different to the colorscheme's opinion.
> 
> I agree. I'll add a guide on readme to make changing colors for the end user easier.
> 

As a user that would be the biggest help and certainly make it usable again

> I do not think following [4 steps](https://github.com/utilyre/barbecue.nvim/blob/1b4a0b6ea6216fee8702857c1e1fcd816abca423/CODE_OF_CONDUCT.md#theming) is THAT much complicated.

I guess that's where we'll disagree. Relatively speaking (compared with other plugins) it's significantly more work but appreciate that versioning will reduce this considerably too.

**Comment by utilyre** [comment]
I'll close this issue as theming docs were added to readme.
