### ISSUE TITLE
is there a way to make the separators have colours?

### ISSUE THREAD

**Issue by Rishabh672003** [utilyre/barbecue.nvim#5]
this is how it looks like now - 
![image](https://user-images.githubusercontent.com/53911515/192113473-1b15c4d6-408a-4332-bd35-a7407e9447b9.png)

my question is - is there a way to add any colors to it? cant seem to find a way to do that i tried adding other icons, just white would also be fine like what colour of the ligature is.

for example like this (its from lunarvim) - 
![image](https://user-images.githubusercontent.com/53911515/192113650-1655e115-73f0-491c-b36f-b81e324deec1.png)

Btw love this plugin

**Comment by Rishabh672003** [comment]
i guess i want a way to modify the default highlights https://github.com/utilyre/barbecue.nvim/blob/63ab05d90e6844d9e5723bb575e9355f58b357ff/lua/barbecue/state.lua#L128

**Comment by utilyre** [comment]
that dimmed color is actually a fallback in case you don't have `NavicSeparator` highlight defined. changing its color is as easy as

```lua
vim.api.nvim_set_hl(0, "NavicSeparator", { link = "Normal" })
```

or with specific hex color

```lua
vim.api.nvim_set_hl(0, "NavicSeparator", { fg = "#ffffff" })
```

**Comment by Rishabh672003** [comment]
oh thanks that solves my issue
