### ISSUE TITLE
[FEAT]: Allow the context texts to follow the colors of the context icons

### ISSUE THREAD

**Issue by xulongwu4** [utilyre/barbecue.nvim#56]
### Requirements

- [X] This feature isn't just a vague idea and has a good practical solution.
- [X] I'm completely sure that this feature fits into this plugin.
- [ ] I'm willing to implement this through a PR.

### Problem

Hi, I love the design of your plugin and want to say thank you first for your excellent work.

Once of my perferences is that I hope the context text could follow the colors of the context icons. Currently, the colors of all context texts are determined by the `theme.context` field, while each context icon can have a different color. I am wondering if you can add an option to allow the text following the context icon to share the color of the context icon.

For example, in the following screenshot, I hope the text `test` to have the same color as the `context_namespace`, i.e, orange color.
![image](https://user-images.githubusercontent.com/16892446/215501384-367bbea7-1a83-4db3-a0ea-2d423404e74e.png)

### Solution Suggestion

Described above.

**Comment by utilyre** [comment]
Hello, enable `context_follow_icon_color` option in your config.
