### ISSUE TITLE
[BUG]: Vim:E36: Not enough room

### ISSUE THREAD

**Issue by tsakirist** [utilyre/barbecue.nvim#61]
### Requirements

- [X] I have scammed [other issues](https://github.com/utilyre/barbecue.nvim/issues) to see if this bug has already been reported.
- [X] This plugin and its dependencies are up to date with the latest commit.
- [ ] I'm willing to fix this through a PR.

### Expected Behavior

There shouldn't be any error from barbecue, when calling the CodeActionMenu command.

### Actual Behavior

Executing `CodeActionMenu` from [nvim-code-action-menu](https://github.com/weilbith/nvim-code-action-menu) causes an error from barbecue (the first time it works, but afterwards calling `CodeActionMenu` results in this error)

![Screenshot from 2023-02-02 21-31-13](https://user-images.githubusercontent.com/20475201/216431373-9597f6a6-7292-48d3-bad2-c4a4d61c8a20.png)

### Neovim Version

```plain text
NVIM v0.9.0-dev-781+gda671b21c
```

### Minimal Configuration

```Lua
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  -- do not remove the colorscheme!
  "folke/tokyonight.nvim",

  {
      'weilbith/nvim-code-action-menu',
      cmd = 'CodeActionMenu',
      keys = { "<leader>ca", "<Cmd>CodeActionMenu<CR>" },
  },

  {
      "neovim/nvim-lspconfig",
      keys = {
	      { "dn", "<Cmd>lua vim.diagnostic.goto_next()<CR>" },
	      { "dp", "<Cmd>lua vim.diagnostic.goto_prev()<CR>" },
      },
      config = function()
	require('lspconfig')['rust_analyzer'].setup{}
      end,
  },

  { "williamboman/mason.nvim", opts = {} },

  {
    "utilyre/barbecue.nvim",
    dependencies = {
      "neovim/nvim-lspconfig",
      "SmiteshP/nvim-navic",
      "nvim-tree/nvim-web-devicons",
    },
    config = function()
      require("barbecue").setup()
    end,
  },
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

-- add anything else here
vim.opt.termguicolors = true
-- do not remove the colorscheme!
vim.cmd([[colorscheme tokyonight]])
```

### Reproduction

Just use CodeActionMenu command when LSP gives you a code-action

**Comment by utilyre** [comment]
I used to have the exact same issue with dressing on renaming stuff, then I compiled and installed the latest commit of nvim (`a26c0ecab610021e6ff6d9d738173a69ecd30fcc` in my case) and it stopped giving me the error.

Your repro also seems not to give any errors on the commit I just mentioned. If updating to the latest nvim didn't solve the issue feel free to re-open.

**Comment by tsakirist** [comment]
I'm on a more recent commit: `NVIM v0.9.0-dev-867+gf9826e1df` and the error still occurs.

Apparently, it doesn't happen with _sumneko-lua_ LSP, but with the rust-analyzer.

With the _rust-analyzer_ the second time that I use `CodeActionMenu` command the error occurs.

If you want I can give you the rust file as-well in case you have a rust/cargo setup and you want to debug it.

**Comment by utilyre** [comment]
I just tested this with rust_analyzer and it didn't break, at least with my version of neovim.

> If you want I can give you the rust file as-well in case you have a rust/cargo setup and you want to debug it.

Yes, please post it.

**Comment by tsakirist** [comment]
Attached in the .zip is the cargo package [example.zip](https://github.com/utilyre/barbecue.nvim/files/10582388/example.zip)

**Comment by utilyre** [comment]
It turns out that the actual culprit of this bug is nvim core. See [nvim/#19464](https://github.com/neovim/neovim/issues/19464)

**Comment by mawkler** [comment]
I also have this issue. I'm on version 0.8.2. Disabling barbecue.nvim solves the issue. I'm also using dressing.nvim.

**Comment by linrongbin16** [comment]
Have the same issue here:
<img width="1730" alt="image" src="https://user-images.githubusercontent.com/6496887/217214942-06b8163d-12ee-4275-8402-e93957904778.png">

**Comment by linrongbin16** [comment]
hi @utilyre  please release a new tag so we can upgrade newer version.

**Comment by utilyre** [comment]
Oh yeah, I forgot to mention. You should use the `fix/E36` branch until the upstream gets fixed.

**Comment by utilyre** [comment]
Just wanted to notify that I rebased the fix branch towrads `main` to get the latest commits. If you're using `lazy.nvim` you'll be fine updating it, on the other hand I think `packer.nvim` doesn't deal with push force very well so be aware of that.

**Comment by BrunoKrugel** [comment]
I am using packer and I am still facing this issue, any fix?

**Comment by utilyre** [comment]
> I am using packer and I am still facing this issue, any fix?

Use `fix/E36` branch

**Comment by cesaralvarod** [comment]
> > I am using packer and I am still facing this issue, any fix?
> 
> Use `fix/E36` branch

It works for me thanks!

**Comment by ispringle** [comment]
Any chance that branch can get rebased again or the fix can be merged into main? Looks like the branch is a bit behind now.

**Comment by utilyre** [comment]
Seems like the upstream issue is not getting any updates. I'll just merge the fix commit to `main` at this point.

**Comment by 3rd** [comment]
Been getting this again with barbecue enabled, does it happen for anyone else?

**Comment by Biggybi** [comment]
> Been getting this again with barbecue enabled, does it happen for anyone else?

Yup, but in neovim-nightly only.

**Comment by joesitton** [comment]
still seeing this in nvim `0.10.1`
