### ISSUE TITLE
">" in the beggining of the filename

### ISSUE THREAD

**Issue by Rishabh672003** [utilyre/barbecue.nvim#7]
![1664606467](https://user-images.githubusercontent.com/53911515/193396860-409b53e2-96f7-4811-9dab-5748f084cc44.png)
i dont know why that ">" appears at the beginning of the winbar on some files 

nvim-version
```
NVIM v0.9.0-dev-1-g4396c3ef2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

**Comment by utilyre** [comment]
Hi, is it fixed now?

**Comment by Rishabh672003** [comment]
yup seems like its fixed, thanks
