### ISSUE TITLE
[BUG]: Dev Icons don't show up

### ISSUE THREAD

**Issue by cs-clarence** [utilyre/barbecue.nvim#77]
### Requirements

- [X] I have skimmed [other issues](https://github.com/utilyre/barbecue.nvim/issues) to see if this bug has already been reported.
- [X] I'm fully certain that this is not a breaking change, see [the latest release](https://github.com/utilyre/barbecue.nvim/releases/latest).
- [X] This plugin and its dependencies are up to date with the latest commit.
- [ ] I'm willing to fix this through a PR.

### Expected Behavior

Winbar to show icons

### Actual Behavior

Winbar only shows rectangles in place of icons

![image](https://user-images.githubusercontent.com/71768661/230751140-2db5c6b5-9c13-4c37-989e-a8dfe79573d1.png)

### Neovim Version

```plain text
0.8.3
```

### Minimal Configuration

```Lua
return {
  {
    "utilyre/barbecue.nvim",
    dependencies = {
      "SmiteshP/nvim-navic",
      "nvim-tree/nvim-web-devicons", -- optional dependency
    },
    config = function()
      local ok, barbecue = pcall(require, "barbecue")

      if not ok then
        vim.notify("barbecue.nvim not installed", vim.log.levels.ERROR)
        return
      end

      barbecue.setup({})
    end,
  },
}
```

### Reproduction

install

**Comment by utilyre** [comment]
Use a font that is patched with [codicons](https://github.com/microsoft/vscode-codicons) or change the `kinds` in your config to the nerd icons that your font already supports.
