### ISSUE TITLE
Including file name, but not parent directories

### ISSUE THREAD

**Issue by KodyVB** [utilyre/barbecue.nvim#8]
Sorry if this is already in the documentation and I'm just being blind, but is there a way to have it so the file name is included in the winbar, but not the path to the file? So if I'm in a different directory from the file I'm working on, it would be:

```
filename.extension > and > so > on
```

Rather than:

```
path > to > filename.extension > and > so > on
```

If it's not included yet, and you do wish to implement this, it could be in variable like `include_path` which defaults to `true` to keep the current default.

**Comment by utilyre** [comment]
you can achieve this through filename-modifiers (see :help for it)

here is an example that substitute everything with an empty string:

```lua
require'barbecue'.setup {
  modifiers = {
    dirname = ":s?.*??",
  },
}
```
