### ISSUE TITLE
[FEAT]: nvim_set_hl should set "default" 

### ISSUE THREAD

**Issue by GnikDroy** [utilyre/barbecue.nvim#84]
### Requirements

- [X] This feature isn't just a vague idea and can have a good practical solution.
- [X] I'm completely sure that this feature fits into this plugin.
- [X] I'm willing to implement this through a PR.

### Problem

Consider a scenario where I am manually setting the highlight groups for barbecue via a colorscheme plugin.

colorscheme plugin loads first -> sets hl groups for barbecue
barbecue loads second -> overrides the hl groups already set by the colorscheme plugin

### Solution Suggestion

Using the default flag avoids this problem completely. This will allow me to keep my highlight groups in a unified location (in the colorscheme file) if I want to. I don't think there are any drawbacks.

### Workaround

Configuring the load order of plugins. If barbecue loads first, the colorscheme plugin correctly overrides the hl groups as expected.

**Comment by utilyre** [comment]
This is the intended behavior, see [theming](https://github.com/utilyre/barbecue.nvim/blob/main/CONTRIBUTING.md#theming).

**Comment by GnikDroy** [comment]
I have read the document. It doesn't mention why the default parameter is not used, though.

Just to be sure, I am talking about `:h nvim_set_hl`
 `• default: Don't override existing definition |:hi-default|` in the following:

https://github.com/utilyre/barbecue.nvim/blob/cd7e7da622d68136e13721865b4d919efd6325ed/lua/barbecue/theme.lua#L140-L144

I notice that any particular group overrides `theme.normal` (possibly to allowing us to change background for all groups)

But none of them set the `default` parameter, even though they are supposed to be "default" values.

I can see that it has its own theming mechanism, like lualine. But unlike lualine, barbecue doesn't have theme = `auto`, or something similar.

Can you explain why this is the intended behaviour?

**Comment by utilyre** [comment]
> I can see that it has its own theming mechanism, like lualine. But unlike lualine, barbecue doesn't have theme = auto, or something similar.

Yes, it does have! See the [Configurations](https://github.com/utilyre/barbecue.nvim#-configuration) section on the readme.

**Comment by GnikDroy** [comment]
Apologies. Somehow missed that.

Still can't figure out why "default" is not set though. What does it break?

**Comment by utilyre** [comment]
`barbecue_*` highlights are meant to be generated on the fly according to the `theme`. So if the `default` option gets enabled, it'd be possible to end up with highlight values that weren't expected.

**Comment by GnikDroy** [comment]
Personally, I think if a colorscheme plugin wants to change a `barbecue_*` highlight manually, they should be allowed to.

Sure, it would then be possible for the actual colorscheme to have discrepancies with the `theme` option from barbecue. But,

1) You can notify users with `vim.notify()` that the `barbecue_*` highlight is being overridden if the `theme` option is also set. So, any "surprises" can be handled gracefully.

2) It is always possible to override highlight groups anyway. So, not using the `default` option doesn't guarantee that the highlight values won't get overridden. It will only depend on the plugin load order. On the other hand, setting `default` gives highest authority of a highlight group to a colorscheme plugin, like it should.

3) It greatly simplifies the maintenance of color scheme plugins since they only have to track changes in their own repositories, rather than in having to check many files across repositories.
