### ISSUE TITLE
Additional highlight groups

### ISSUE THREAD

**Issue by dlvhdr** [utilyre/barbecue.nvim#9]
1. I would like to color the modified icon as yellow
2. I would like to have the ability to set the background color of the whole winbar

Thanks for the awesome plugin!

**Comment by dlvhdr** [comment]
Thanks!

> For this you have to override all the highlight groups mentioned [here](https://github.com/utilyre/barbecue.nvim#-highlight-groups) to have a background color.

It might be worth it for you to add a option to set a background by internally adding bg to all those hl groups.

**Comment by utilyre** [comment]
Now you should be able to remove that inline highlight and see if it works. In case it doesn't add this to your config (replace \<yellow\> with any hex color you desire)

```lua
vim.api.nvim_set_hl(0, "BarbecueMod", { fg = "#<yellow>" })
```

---

> It might be worth it for you to add a option to set a background by internally adding bg to all those hl groups.

To be honest, it is your colorscheme's job to determine what colors will be used in your editor. Therefore plugins only make use of those highlight groups.

**Comment by dlvhdr** [comment]
Thanks, this works!
